export const menuData = {
  categorias: [
    {
      nome: "Algodão Doce",
      itens: [
        { nome: "Corote com Beats", preco: 35, imagem: "/corote-beats.jpg" },
        { nome: "Lagoa Azul", preco: 35, imagem: "/lagoa-azul.jpg" },
        { nome: "Tuti Frut - Corote de Tuti Frut e Uva", preco: 35, imagem: "/corote-tuti-frut.jpg" },
      ],
    },

    {
      nome: "Cervejas",
      itens: [
        { nome: "Amstel", preco: 10, imagem: "/cervejas/amstel.jpeg" },
        { nome: "Amstel 473ml", preco: 6.5, imagem: "/cervejas/amstel-473.jpg" },
        { nome: "Brahma 473ml", preco: 8, imagem: "/cervejas/brahma-473.jpg" },
        { nome: "Brahma Chopp", preco: 16, imagem: "/cervejas/brahma.jpg" },
        { nome: "Brahma Malzbier Long Neck", preco: 12, imagem: "/cervejas/brahma-malzbier.jpg" },
        { nome: "Budweiser 473ml", preco: 8, imagem: "/cervejas/budweiser-473.jpg" },
        { nome: "Budweiser Long Neck", preco: 10, imagem: "/cervejas/budweiser.jpg" },
        { nome: "Corona Long Neck", preco: 11, imagem: "/cervejas/corona.jpg" },
        { nome: "Heineken 473ml", preco: 8, imagem: "/cervejas/heineken-473.jpg" },
        { nome: "Heineken Long Neck", preco: 10, imagem: "/cervejas/heineken-long.jpg" },
        { nome: "Litro Original", preco: 18, imagem: "/cervejas/original-litro.png" },
        { nome: "Original 473ml", preco: 8, imagem: "/cervejas/original-lata.jpg" },
        { nome: "Patagônia Long Neck", preco: 13, imagem: "/cervejas/patagonia-long.jpg" },
        { nome: "Skol Beats", preco: 12, imagem: "/cervejas/beats.jpg" },
        { nome: "Smirnoff Ice", preco: 16, imagem: "/cervejas/ice.jpg" },
        { nome: "Spaten 473ml", preco: 8, imagem: "/cervejas/spaten.jpg" },
        { nome: "Spaten Long Neck", preco: 10, imagem: "/cervejas/spaten-long.jpg" },
        { nome: "Stella Artois Long Neck", preco: 10, imagem: "/cervejas/stella-artois.jpg" },
        { nome: "Stella Gold Long Neck", preco: 10, imagem: "/cervejas/stella.jpg" },
      ].sort((a, b) => a.nome.localeCompare(b.nome)),
    },

    {
      nome: "Combos",
      itens: [
        { nome: "Absolut 1L + Gelo + Energético 2L", preco: 200, imagem: "/absolut-combo.jpg" },
        { nome: "Ballantine's + Gelo + Energético 2L", preco: 160, imagem: "/ballantines-combo.jpg" },
        { nome: "Black Stone + Gelo + Energético 2L", preco: 80, imagem: "/black-stone-combo.jpg" },
        { nome: "Gin Rocks + Gelo + Energético 2L", preco: 100, imagem: "/gin-rocks-combo.jpg" },
        { nome: "Jack Canela + Gelo + Energético 2L", preco: 250, imagem: "/jack-canela-combo.jpg" },
        { nome: "Jack Maçã + Gelo + Energético 2L", preco: 250, imagem: "/jack-maca-combo.jpg" },
        { nome: "Jack Mel + Gelo + Energético 2L", preco: 250, imagem: "/jack-mel-combo.jpg" },
        { nome: "Jack Original + Gelo + Energético 2L", preco: 250, imagem: "/jack-original-combo.jpg" },
        { nome: "Licor 43 Aperol + Lata Refri + Gelo", preco: 280, imagem: "/licor-43-combo.jpg" },
        { nome: "Natu + Gelo + Energético 2L", preco: 70, imagem: "/natu-combo.jpg" },
        { nome: "Old Parr + Gelo + Energético 2L", preco: 250, imagem: "/old-parr-combo.jpg" },
        { nome: "Popokelvis + Gelo + Energético 2L", preco: 80, imagem: "/popokelvis-combo.jpg" },
        { nome: "Smirnoff + Gelo + Energético 2L", preco: 120, imagem: "/smirnoff-combo.jpg" },
        { nome: "White Horse + Gelo + Energético 2L", preco: 150, imagem: "/white-horse-combo.jpg" },
      ],
    },

    {
      nome: "Copos e Drinks",
      itens: [
        { nome: "Caipirinha Cachaça", preco: 25, imagem: "/caipirinha-cachaca.jpg" },
        { nome: "Caipirinha com Vodka", preco: 30, imagem: "/caipirinha-vodka.jpg" },
        { nome: "Copo Absolut + Energético e Gelo de Sabor", preco: 30, imagem: "/copo-absolut.jpg" },
        { nome: "Copo Balena", preco: 45, imagem: "/copo-balena.jpg" },
        { nome: "Copo Gin com Suco", preco: 10, imagem: "/copo-gin.jpg" },
        { nome: "Copo Jack + Gelo de Sabor", preco: 30, imagem: "/copo-jack.jpg" },
        { nome: "Copo Licor 43 Aperol e Refri", preco: 30, imagem: "/copo-licor-43.jpg" },
        { nome: "Corona com Aperol", preco: 15, imagem: "/corona-aperol.jpg" },
        { nome: "Piña Colada", preco: 30, imagem: "/pina-colada.jpg" },
      ],
    },

    {
      nome: "Garrafas",
      itens: [
        { nome: "Absolut Vanilia", preco: 168.22, imagem: "/garrafas/absolut-vanilia.jpg" },
        { nome: "Absolut Vodka", preco: 157.6, imagem: "/garrafas/absolut-vodka.jpg" },
        { nome: "Afrika", preco: 88, imagem: "/garrafas/afrika.jpg" },
        { nome: "Aperol", preco: 88.45, imagem: "/garrafas/aperol.jpg" },
        { nome: "Ballantines", preco: 191.4, imagem: "/garrafas/ballantines.jpg" },
        { nome: "Ballena", preco: 191.4, imagem: "/garrafas/ballena.jpg" },
        { nome: "Chivas", preco: 173.49, imagem: "/garrafas/chivas.jpg" },
        { nome: "Cold Brew", preco: 281.38, imagem: "/garrafas/cold-brew.jpg" },
        { nome: "Gentleman Jack", preco: 250.5, imagem: "/garrafas/gentleman-jack.jpg" },
        { nome: "Gin Rocks", preco: 53.9, imagem: "/garrafas/gin-rocks.jpg" },
        { nome: "Jack Daniels Apple", preco: 200, imagem: "/garrafas/jack-daniels-apple.jpg" },
        { nome: "Jack Daniels Fire", preco: 200, imagem: "/garrafas/jack-daniels-fire.jpg" },
        { nome: "Jack Daniels Single Barrel", preco: 270, imagem: "/garrafas/jack-daniels-single-barrel.jpg" },
        { nome: "Jack Daniels Whiskey", preco: 200, imagem: "/garrafas/jack-daniels-whiskey.jpg" },
        { nome: "Jose Cuervo", preco: 278.46, imagem: "/garrafas/jose-cuervo-white.jpg" },
        { nome: "Jose Cuervo", preco: 278.46, imagem: "/garrafas/jose-cuervo-yellow.jpg" },
        { nome: "Martini", preco: 69.8, imagem: "/garrafas/martini.jpg" },
        { nome: "Natu Nobilis", preco: 80, imagem: "/garrafas/natu-nobilis.jpg" },
        { nome: "Old Parr", preco: 199.39, imagem: "/garrafas/old-parr.jpg" },
        { nome: "Red Label", preco: 183, imagem: "/garrafas/red-label.jpg" },
        { nome: "Tanqueray", preco: 227.74, imagem: "/garrafas/tanqueray.jpg" },
        { nome: "White Horse", preco: 129.8, imagem: "/garrafas/white-horse.jpg" },
      ],
    },

    {
      nome: "Cigarros",
      itens: [
        { nome: "Camel Berry", preco: 18, imagem: "/cigarros/camel-berry.jpg" },
        { nome: "Camel Blue", preco: 9, imagem: "/cigarros/camel-blue.jpg" },
        { nome: "Camel Menthol", preco: 18, imagem: "/cigarros/camel-menthol.jpg" },
        { nome: "Camel Purple Beach", preco: 12.25, imagem: "/cigarros/camel-purple-beach.jpg" },
        { nome: "Dunhill", preco: 13.5, imagem: "/cigarros/dunhill.jpg" },
        { nome: "Dunhill Double Refresh", preco: 20, imagem: "/cigarros/dunhill-double-refresh.jpg" },
        { nome: "L & M", preco: 7.5, imagem: "/cigarros/l-&-m.jpg" },
        { nome: "Lucky Strike Fresh Mint", preco: 12.5, imagem: "/cigarros/lucky-strike-fresh-mint.jpg" },
        { nome: "Lucky Strike Red", preco: 8.5, imagem: "/cigarros/lucky-strike-red.jpg" },
        { nome: "Malboro", preco: 8.5, imagem: "/cigarros/malboro.jpg" },
        { nome: "Rothmans Double Click", preco: 8.5, imagem: "/cigarros/rothmans-double-click.jpg" },
        { nome: "Rothmans Kingsize Blue", preco: 8.5, imagem: "/cigarros/rothmans-kingsize-blue.jpg" },
        { nome: "Rothmans of London", preco: 8.5, imagem: "/cigarros/rothmans-of-london.jpg" },
      ].sort((a, b) => a.nome.localeCompare(b.nome)),
    },
  ],
};
